name              'osl-rt'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
issues_url        'https://github.com/osuosl-cookbooks/osl-rt/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-rt'
license           'Apache-2.0'
chef_version      '>= 16.0'
description       'Installs/Configures an instance of Request Tracker'
version           '1.0.2'

depends           'certificate'
depends           'osl-apache'
depends           'osl-acme'
depends           'osl-firewall'
depends           'osl-git'
depends           'osl-mysql'
depends           'osl-nrpe'
depends           'osl-php'
depends           'osl-postfix'
depends           'osl-rsync'
depends           'osl-selinux'
depends           'yum-osuosl'
depends           'perl'

supports          'almalinux', '~> 8.0'
supports          'almalinux', '~> 9.0'
