name              'osl-rt'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
issues_url        'https://github.com/osuosl-cookbooks/osl-rt/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-rt'
license           'Apache-2.0'
chef_version      '>= 16.0'
description       'Installs/Configures an instance of Request Tracker'
version           '2.2.0'

depends           'osl-apache'
depends           'osl-mysql'
depends           'osl-postgresql'
depends           'osl-postfix'
depends           'yum-osuosl'
depends           'perl', '~> 1.2.2'

supports          'almalinux', '~> 8.0'
supports          'almalinux', '~> 9.0'
supports          'almalinux', '~> 10.0'
