name             'osl-rt-test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
description      'Test cookbook for request tracker'
version          '0.1.0'
depends          'osl-rt'
